//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Plane.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHANGBAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHANGBAY()
        {
            this.SANBAYs = new HashSet<SANBAY>();
            this.SANBAYs1 = new HashSet<SANBAY>();
        }
    
        public Nullable<System.DateTime> ThoiGianKhoiHanh { get; set; }
        public Nullable<System.DateTime> ThoiGianBay { get; set; }
        public string MaChangBay { get; set; }
        public string LoaiChangBay { get; set; }
        public string IDCB { get; set; }
        public string Sohieu { get; set; }
    
        public virtual CHUYENBAY CHUYENBAY { get; set; }
        public virtual MAYBAY MAYBAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANBAY> SANBAYs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANBAY> SANBAYs1 { get; set; }
    }
}
