//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Plane.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHOADON
    {
        public string MACTHD { get; set; }
        public string MaHoaDon { get; set; }
        public string MaVe { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual VeMayBay VeMayBay { get; set; }
    }
}
