//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Plane.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO
    {
        public int SoLuong { get; set; }
        public string IDCB { get; set; }
        public string MaLoaiVe { get; set; }
    
        public virtual CHUYENBAY CHUYENBAY { get; set; }
        public virtual LOAIVE LOAIVE { get; set; }
    }
}
