//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Plane.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAYBAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAYBAY()
        {
            this.CHANGBAYs = new HashSet<CHANGBAY>();
        }
    
        public string Sohieu { get; set; }
        public string IDHK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHANGBAY> CHANGBAYs { get; set; }
        public virtual HANGHANGKHONG HANGHANGKHONG { get; set; }
    }
}
