//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Plane.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANBAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANBAY()
        {
            this.NHAGAs = new HashSet<NHAGA>();
            this.CHANGBAYs = new HashSet<CHANGBAY>();
            this.CHANGBAYs1 = new HashSet<CHANGBAY>();
        }
    
        public string IATA { get; set; }
        public string TenSanBay { get; set; }
        public string QuocGia { get; set; }
        public string ThanhPho { get; set; }
        public string DiaChi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHAGA> NHAGAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHANGBAY> CHANGBAYs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHANGBAY> CHANGBAYs1 { get; set; }
    }
}
