//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Plane.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VeMayBay
    {
        public string MaVe { get; set; }
        public string Cua { get; set; }
        public string ChoNgoi { get; set; }
        public string TrangThai { get; set; }
        public string LoaiHanhLy { get; set; }
        public int ThanhTien { get; set; }
        public string IDCB { get; set; }
        public string CCCD { get; set; }
        public string MaLoaiVe { get; set; }
    
        public virtual CHUYENBAY CHUYENBAY { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual LOAIVE LOAIVE { get; set; }
    }
}
